import { WHATSAPP_NUMBER, PRECIOS } from './config.js';
import { YAMAHA_MESES, VIDEOS_GALERIA, COSTOS_CALCULADORA, TOTALES } from './data.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], nf=new Intl.NumberFormat('es-CO');
const money=n=>`$${nf.format(n)}`;
function wa(text){return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`}
function wireWhatsApp(){ $$('.js-whatsapp').forEach(a=>{a.href=wa('Hola Eduar. Queremos pedir un diagnóstico gratis para nuestro negocio.');a.addEventListener('click',()=>window.gtag?.('event','contact_whatsapp'));}); const calcLink=$('#calc-whatsapp'); if(calcLink) calcLink.addEventListener('click',()=>window.gtag?.('event','contact_whatsapp')); }
const total={id:'total',nombre:'6 meses',fb_vis:YAMAHA_MESES.reduce((s,m)=>s+m.fb_vis,0),fb_pauta:YAMAHA_MESES.reduce((s,m)=>s+m.fb_pauta,0),fb_org:YAMAHA_MESES.reduce((s,m)=>s+m.fb_org,0),ig_vis:YAMAHA_MESES.reduce((s,m)=>s+m.ig_vis,0),conversaciones:TOTALES.conversaciones,inversion:TOTALES.inversion};
function renderMonths(){const holder=$('#month-tabs');[...YAMAHA_MESES,total].forEach(m=>{const b=document.createElement('button');b.type='button';b.role='tab';b.dataset.id=m.id;b.textContent=m.nombre;b.setAttribute('aria-selected',m.id==='total');b.addEventListener('click',()=>{ $$('#month-tabs button').forEach(x=>x.setAttribute('aria-selected','false'));b.setAttribute('aria-selected','true');renderMetrics(m)});holder.append(b)});renderMetrics(total)}
function renderMetrics(m){const views=m.fb_vis+m.ig_vis,cost=Math.round(m.inversion/m.conversaciones);$('#metric-conversations').textContent=nf.format(m.conversaciones);$('#metric-investment').textContent=money(m.inversion);$('#metric-views').textContent=nf.format(views);$('#metric-cost').textContent=money(cost)}
function renderVideos(){const holder=$('#video-gallery');holder.innerHTML=VIDEOS_GALERIA.map((v,i)=>`<article class="video-card"><div class="phone"><video src="${v.archivo}" muted loop playsinline preload="none" aria-label="Video vertical ${i+1}"></video><button type="button" aria-label="Activar sonido del video ${i+1}">◉</button></div><strong>${(v.vistas/1000).toLocaleString('es-CO',{maximumFractionDigits:1})} mil</strong></article>`).join('');const videos=$$('.video-card video');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.play().catch(()=>{})}else e.target.pause()}),{threshold:.55});videos.forEach(v=>io.observe(v));$$('.video-card button').forEach((b,i)=>b.addEventListener('click',()=>{videos.forEach((v,j)=>{v.muted=j!==i});videos[i].play().catch(()=>{})}))}
function renderPricing(){const holder=$('#pricing-grid');const order=['landingEsencial','landingPremium','contenido','ads','fullStack'];holder.innerHTML=order.map((key,i)=>{const p=PRECIOS[key];return `<article class="price-card ${key==='fullStack'?'featured':''}"><p class="eyebrow">${i===4?'Plan destacado':'Servicio'}</p><h3>${p.nombre}</h3><div class="price">${p.precio}</div><p>${p.tipo} · ${p.resumen}</p><details><summary>Ver alcance</summary><ul>${p.incluye.map(x=>`<li>${x}</li>`).join('')}</ul></details><a class="button ${key==='fullStack'?'button-red':'button-dark'}" href="${wa(`Hola Eduar. Quiero cotizar el plan ${p.nombre}.`)}">Cotizar este plan</a></article>`}).join('')}
function renderFaq(){const qs=[['¿La inversión en anuncios está incluida?','No. La pagas directo a Meta desde tu cuenta; el servicio cubre estrategia, creación, gestión y optimización.'],['¿Garantizas ventas?','No. Lo que controlamos es el contenido, la pauta y el costo por conversación; las ventas dependen también de tu oferta y de cómo atiendes los mensajes.'],['¿Cuánto tarda en verse algo?','Las primeras conversaciones llegan desde unas horas hasta un día después de activar la campaña. La optimización fina se ve con las semanas.'],['¿Cuánto tarda mi landing?','Entre 10 y 15 días, ya publicada con dominio y hosting.'],['¿De quién es el contenido?','Del cliente; se entrega en los formatos acordados.'],['¿Hay permanencia mínima?','En el plan Full Stack no.'],['¿Cómo se paga?','La landing, 50% al empezar y 50% al entregar. Los planes mensuales, por adelantado cada mes.'],['¿Qué pasa con el dominio y el hosting?','El primer año va incluido en el precio de la landing. Desde el segundo año, la renovación cuesta desde $250.000 al año.']];$('#faq-list').innerHTML=qs.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}
function calc(){const inv=+$('#investment').value,cost=+$('#offer').value,rate=Math.max(0,Math.min(100,+$('#close-rate').value||0)),con=Math.floor(inv/cost);$('#investment-output').textContent=money(inv);$('#estimated-conversations').textContent=nf.format(con);$('#estimated-clients').textContent=nf.format(Math.floor(con*rate/100));$('#calc-whatsapp').href=wa(`Hola Eduar. Simulé una inversión de ${money(inv)} al mes con ${$('#offer').selectedOptions[0].textContent} (${money(cost)} por conversación). La estimación es de ${nf.format(con)} conversaciones y ${nf.format(Math.floor(con*rate/100))} clientes con una tasa de cierre del ${rate}%. Quiero hablar de estos números.`)}
function setup(){const sel=$('#offer');if(sel){Object.entries(COSTOS_CALCULADORA).forEach(([label,value])=>sel.add(new Option(`${label} · ${money(value)} por conversación`,value)));['input','change'].forEach(ev=>{$('#investment').addEventListener(ev,calc);$('#offer').addEventListener(ev,calc);$('#close-rate').addEventListener(ev,calc)});calc();}$('#contact-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);location.href=wa(`Hola Eduar. Somos ${d.get('nombre')} y nuestro negocio es de ${d.get('negocio')}. ${d.get('mensaje')}`)});const menu=$('.menu-toggle');menu.addEventListener('click',()=>{$('#nav-links').classList.toggle('open');menu.setAttribute('aria-expanded',$('#nav-links').classList.contains('open'))});$$('.nav-links a').forEach(a=>a.addEventListener('click',()=>$('#nav-links').classList.remove('open')));const lights=$$('.shift-lights i');const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;function scrollLights(){const p=scrollY/(document.documentElement.scrollHeight-innerHeight);lights.forEach((l,i)=>l.classList.toggle('active',reduced?i<6:i<Math.ceil(p*10)))}addEventListener('scroll',scrollLights,{passive:true});scrollLights();wireWhatsApp();renderMonths();renderVideos();renderPricing();renderFaq()}setup();
